name: foo
description: Foo Prototyp

version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0" # original value: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  pedantic: ^1.9.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.6+1
  intl: ^0.16.1
  location: ^3.2.4
  path_provider: ^1.6.8
  http: ^0.12.2
  loading_overlay: ^0.2.1
  chips_choice: ^2.0.1
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^3.3.5
  flutter_launcher_icons: ^0.8.1
  dash_chat: ^1.1.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  integration_test: ^1.0.0  # integration testing

# integration testing: https://flutter.dev/docs/testing/integration-tests
flutter_test:
  sdk: flutter
flutter_driver:
  sdk: flutter


dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "resources/logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
